export enum ExcelLoadEnumerator {
  values = "values",
  address = "address",
  rows = "rows",
  items = "items",
  columns = "columns",
  name = "name",
  columnCount = "columnCount",
  count = "count",
  items_name = "items/name",
  address_values = "address, values",
  rowCount = "rowCount",
  columnIndex = "columnIndex",
  autoFilter = "autoFilter",
  protection_protected = "protection/protected",
  dataValidation = "dataValidation",
  numberFormat = "numberFormat",
}

export enum ModalTypesEnumerator {
  POLICIES = "POLICIES",
  UNMAPPED_COLUMNS = "UNMAPPED_COLUMNS",
  GROSS_EARNED_PREMIUM = "GROSS_EARNED_PREMIUM",
  GROSS_WRITTEN_PREMIUM = "GROSS_WRITTEN_PREMIUM"
}

export enum AlphabetsEnumerator {
  A = "A",
  B = "B",
  C = "C",
  D = "D",
  E = "E",
  F = "F",
  G = "G",
  H = "H",
  I = "I",
  J = "J",
  K = "K",
  L = "L",
  M = "M",
  N = "N",
  O = "O",
  P = "P",
  Q = "Q",
  R = "R",
  S = "S",
  T = "T",
  U = "U",
  V = "V",
  W = "W",
  X = "X",
  Y = "Y",
  Z = "Z",
}
